name: quick_drink_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


